version: '3.8'

services:
  gas-platform:
    image: gas-platform
    build: .
    ports:
      - "8501:8501"
      - "8502-8510:8502-8510"
    volumes:
      - ./integrator_config:/app/integrator_config
      - ./database:/app/database
      - ./EUR_Predict:/app/EUR_Predict
      - ./rule_reasoning:/app/rule_reasoning
      - ./yumen_gas:/app/yumen_gas
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - SERVER_IP=121.43.99.236
    restart: unless-stopped
    container_name: gas-platform-app
